package.json, pnpm-lock.yaml, src/darwin.ts, src/type.ts, src/utils.ts
Copy from the original path to another path so that a reset operation can be performed when there is a problem.
=> feat(api): improve path and add reset path

src/darwin.ts
Deps:
* https://github.com/oomol-lab/ovm-osx-toolchain/pull/2
=> refactor(process): exit child process when nodejs process exit

src/darwin.ts
https://oomol.atlassian.net/browse/OOM-832
=> feat(vm): sync clock when resume vm

package.json, pnpm-lock.yaml, src/darwin.ts, src/utils.ts
Ref: https://github.com/oomol-lab/ovm-core/pull/31
=> refactor(vm): add disk support

src/darwin.ts
Ref: https://github.com/oomol-lab/ovm-core/pull/33
=> refactor(port): remove port export api

src/darwin.ts
https://oomol.atlassian.net/browse/OOM-927
https://oomol.atlassian.net/browse/OOM-837
=> fix(process): no send close event when process exit

src/darwin.ts
Ref: https://github.com/oomol-lab/ovm-core/pull/34
=> perf(vm): improve mount process

src/darwin.ts
Because the service needs to be enabled, if not enabled, a link needs to be created manually. In order to reduce the complexity of the current project, this functionality is migrated to ovm-core.
Ref: https://github.com/oomol-lab/ovm-core/pull/36
=> fix(ready): ready time out

src/darwin.ts, src/utils.ts
https://oomol.atlassian.net/browse/OOM-939
=> feat(vm): auto set timezone

src/darwin.ts
Ref: https://github.com/spf13/cobra/issues/613#issuecomment-357706597
=> fix(spawn): power-save-mode param invalid

src/darwin.ts, src/type.ts
https://oomol.atlassian.net/browse/OOM-1349
Ref: https://github.com/oomol-lab/ovm/pull/43
=> feat(ovm): support extends share dir

src/index.ts, src/request.ts, src/type.ts, src/windows.ts
Ref: https://github.com/oomol/ovm-win/pull/51
=> refactor(windows): support run and prepare cmd

src/index.ts, src/type.ts
Ref: https://github.com/oomol-lab/ovm/pull/50
=> refactor(darwin): improve exit notify in event

package.json
Ref: https://github.com/oomol-lab/ovm-win/compare/v1.0.0-RC6...v1.0.0-RC7
=> chore(version): upgrade version to 2.0.0-rc.19

package.json
Ref: https://github.com/oomol-lab/ovm-core/releases/tag/v1.0.2
=> chore(version): upgrade version to 2.0.0-rc.21

package.json
Ref: https://github.com/oomol-lab/ovm/pull/55
=> chore(version): upgrade version to 2.0.0-rc.25

package.json
update ovm-core to v1.0.4
Ref: https://github.com/oomol-lab/ovm-core/pull/74
=> chore(version): update version to 2.0.0-rc.31

package.json, scripts/resource.json
Ref: https://github.com/oomol-lab/ovm-libexec/pull/7
=> chore(version): upgrade version to 2.0.0-rc.38

scripts/resource.json, src/windows.ts
Upstream: https://github.com/oomol-lab/ovm-win/pull/89
=> feat(win): support migrate ovm image

scripts/download.mjs, scripts/resource.json
ref: https://github.com/oomol-lab/ovm-win/releases/tag/v1.2.0
=> chore(deps): upgrade ovm-win to 1.2.0

scripts/resource.json
Ref: https://github.com/oomol-lab/ovm-win/compare/v1.2.2...v1.2.3
=> chore(dep): update ovm-win to v1.2.3

package.json
Signed-off-by: Kevin Cui <bh@bugs.cc>
=> chore(version): upgrade version to v2.1.1
